### ISSUE TITLE
I can't install dext, what version of Deno do I need?

### ISSUE THREAD

**Issue by tubone24** [lucacasonato/dext.ts#80]
I tried to install dext according to the instructions in the README, but I got an error.

Command
```
deno install --allow-read --allow-write --allow-env --allow-net --allow-run --unstable -f -n dext https://deno.land/x/dext@0.10.5/cli.ts
```

Error
```
Check https://deno.land/x/dext@0.10.5/cli.ts
error: TS2339 [ERROR]: Property 'emit' does not exist on type 'typeof Deno'.
        const result = await Deno.emit(id, {
                                  ~~~~
    at https://raw.githubusercontent.com/denofn/denopack/8bae39bef47e532a1e8d0f6700b72a2192f7bca4/plugin/typescriptTransform/mod.ts:19:35

TS2339 [ERROR]: Property 'emit' does not exist on type 'typeof Deno'.
  const { diagnostics, files: emitFiles } = await Deno.emit(importee, {
                                                       ~~~~
    at https://raw.githubusercontent.com/denofn/denopack/8bae39bef47e532a1e8d0f6700b72a2192f7bca4/plugin/typescriptCompile/mod.ts:45:56

Found 2 errors.

```

My environment is as below.

```
> deno --version

deno 1.6.3 (release, x86_64-pc-windows-msvc)
v8 8.8.294
typescript 4.1.3
```

Is it due to the fact that the Deno version is too high?

**Comment by tubone24** [comment]
I solved the problem myself.

v1.8.0 or later with `Deno.emit` support and GitHub Acitons
I installed v1.8.0 or later, which supports `Deno.emit`, and v1.8.2, which is supported by GitHub Acitons' setup-deno, and it worked.

- [Deno 1.8 Release Notes](https://deno.com/blog/v1.8)
- [Setup Deno/Specific stable](https://github.com/denoland/setup-deno#specific-stable)

```
> deno --version

deno 1.8.2 (release, x86_64-pc-windows-msvc)
v8 9.0.257.3
typescript 4.2.2


> deno install --allow-read --allow-write --allow-env --allow-net --allow-run --unstable -f -n dext https://deno.land/x/dext@0.10.5/cli.ts
Check https://deno.land/x/dext@0.10.5/cli.ts
✅ Successfully installed dext
```

By the way, I upgraded the deno version to the latest 1.12.2 and ran the same command, but I still could not install it with the following error.

```
> deno install --allow-read --allow-write --allow-env --allow-net --allow-run --unstable -f -n dext 

https://deno.land/x/dext@0.10.5/cli.ts
Check https://deno.land/x/dext@0.10.5/cli.ts
error: TS5056 [ERROR]: Cannot write file 'https://cdn.dreg.dev/package/@types/estree@0.0.45.js' because it would be overwritten by multiple input files.

```

I was using an older version of Deno, v1.6.3, because it was necessary for [Aleph.js](https://alephjs.org/docs/get-started) requirements, but I felt it was necessary to include the Deno version in the **README** to avoid confusion for users.

**Comment by tubone24** [comment]
According to my research, the suitable Deno version for Dext.js seems to be between v1.7.x and v1.9.x.

I've experimented with GitHub Acitons.

https://github.com/tubone24/dext-deno-runtime-ditect/actions/runs/1074204697

**Comment by baetheus** [comment]
I believe the 

> I solved the problem myself.
> 
> v1.8.0 or later with `Deno.emit` support and GitHub Acitons
> I installed v1.8.0 or later, which supports `Deno.emit`, and v1.8.2, which is supported by GitHub Acitons' setup-deno, and it worked.
> 
>     * [Deno 1.8 Release Notes](https://deno.com/blog/v1.8)
> 
>     * [Setup Deno/Specific stable](https://github.com/denoland/setup-deno#specific-stable)
> 
> 
> ```
> > deno --version
> 
> deno 1.8.2 (release, x86_64-pc-windows-msvc)
> v8 9.0.257.3
> typescript 4.2.2
> 
> 
> > deno install --allow-read --allow-write --allow-env --allow-net --allow-run --unstable -f -n dext https://deno.land/x/dext@0.10.5/cli.ts
> Check https://deno.land/x/dext@0.10.5/cli.ts
> ✅ Successfully installed dext
> ```
> 
> By the way, I upgraded the deno version to the latest 1.12.2 and ran the same command, but I still could not install it with the following error.
> 
> ```
> > deno install --allow-read --allow-write --allow-env --allow-net --allow-run --unstable -f -n dext 
> 
> https://deno.land/x/dext@0.10.5/cli.ts
> Check https://deno.land/x/dext@0.10.5/cli.ts
> error: TS5056 [ERROR]: Cannot write file 'https://cdn.dreg.dev/package/@types/estree@0.0.45.js' because it would be overwritten by multiple input files.
> ```
> 
> I was using an older version of Deno, v1.6.3, because it was necessary for [Aleph.js](https://alephjs.org/docs/get-started) requirements, but I felt it was necessary to include the Deno version in the **README** to avoid confusion for users.

I believe this is a --no-check problem as noted in #76.

**Comment by tubone24** [comment]
@baetheus 

Thanks for replying.
You're right, I was able to install the dext.ts without any problems on all Deno versions by adding --no-check.

https://github.com/tubone24/dext-deno-runtime-ditect/actions/runs/1129478519
